# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 250)
        Form.setMinimumSize(QtCore.QSize(300, 150))
        Form.setMaximumSize(QtCore.QSize(400, 250))
        Form.setStyleSheet(
            "QWidget {\n"
            "    background-color: #2C2F33;  \n"
            "    color: #FFFFFF;             \n"
            "}"
        )
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(30, -1, 30, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(
            self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.errorLabel = QtWidgets.QLabel(parent=Form)
        self.errorLabel.setStyleSheet(
            "QLabel#errorLabel {\n"
            "    color: #FF4D4D;  \n"
            "    font-size: 9px;\n"
            "    font-weight: bold;\n"
            "    padding: 5px;\n"
            "    background-color: #2C2F33;  \n"
            "}"
        )
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setStyleSheet(
            "QLineEdit {\n"
            "    border: 2px solid #444; \n"
            "    border-radius: 5px;\n"
            "    background-color: #2C2F33; \n"
            "    color: #FFF;\n"
            "    padding: 5px;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    border: 2px solid #7289DA;\n"
            "}"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setStyleSheet(
            "QLineEdit {\n"
            "    border: 2px solid #444; \n"
            "    border-radius: 5px;\n"
            "    background-color: #2C2F33; \n"
            "    color: #FFF;\n"
            "    padding: 5px;\n"
            "}\n"
            "QLineEdit:focus {\n"
            "    border: 2px solid #7289DA;\n"
            "}"
        )
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pushButton.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #7289DA; \n"
            "    color: #FFF; \n"
            "    border-radius: 5px;\n"
            "    padding: 10px;\n"
            "}\n"
            "QPushButton:hover {\n"
            "    background-color: #5B6EAE;\n"
            "}\n"
            "QPushButton:pressed {\n"
            "    background-color: #4E5E92;\n"
            "}\n"
            ""
        )
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(
            self.pushButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Авторизация"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Почта"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Пароль"))
        self.pushButton.setText(_translate("Form", "Войти"))
