# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 350)
        Form.setMinimumSize(QtCore.QSize(700, 350))
        Form.setMaximumSize(QtCore.QSize(700, 350))
        self.sections = QtWidgets.QPushButton(parent=Form)
        self.sections.setGeometry(QtCore.QRect(20, 210, 190, 81))
        self.sections.setObjectName("sections")
        self.vacations = QtWidgets.QPushButton(parent=Form)
        self.vacations.setGeometry(QtCore.QRect(490, 210, 190, 81))
        self.vacations.setObjectName("vacations")
        self.users = QtWidgets.QPushButton(parent=Form)
        self.users.setGeometry(QtCore.QRect(260, 210, 190, 81))
        self.users.setObjectName("users")
        self.userinfo = QtWidgets.QLabel(parent=Form)
        self.userinfo.setGeometry(QtCore.QRect(30, 10, 511, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.userinfo.setFont(font)
        self.userinfo.setObjectName("userinfo")
        self.access_info = QtWidgets.QLabel(parent=Form)
        self.access_info.setGeometry(QtCore.QRect(30, 70, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.access_info.setFont(font)
        self.access_info.setObjectName("access_info")
        self.profile_button = QtWidgets.QPushButton(parent=Form)
        self.profile_button.setGeometry(QtCore.QRect(550, 20, 141, 31))
        self.profile_button.setObjectName("profile_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sections.setText(_translate("Form", "Отделы"))
        self.vacations.setText(_translate("Form", "Отпуска"))
        self.users.setText(_translate("Form", "Сотрудники"))
        self.userinfo.setText(_translate("Form", "TextLabel"))
        self.access_info.setText(_translate("Form", "Пользователь"))
        self.profile_button.setText(_translate("Form", "Профиль"))
