# Form implementation generated from reading ui file 'main_window_rew.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 350)
        Form.setMinimumSize(QtCore.QSize(700, 350))
        Form.setMaximumSize(QtCore.QSize(700, 350))
        Form.setStyleSheet("QWidget {\n"
"    background-color: #2C2F33;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px; /* Белая обводка шириной 2px */\n"
"    padding: 5px 10px;      /* Внутренние отступы */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#3A3D42; /* Цвет при наведении */\n"
"}")
        self.sections = QtWidgets.QPushButton(parent=Form)
        self.sections.setGeometry(QtCore.QRect(20, 210, 190, 81))
        self.sections.setObjectName("sections")
        self.vacations = QtWidgets.QPushButton(parent=Form)
        self.vacations.setGeometry(QtCore.QRect(490, 210, 190, 81))
        self.vacations.setObjectName("vacations")
        self.users = QtWidgets.QPushButton(parent=Form)
        self.users.setGeometry(QtCore.QRect(260, 210, 190, 81))
        self.users.setObjectName("users")
        self.userinfo = QtWidgets.QLabel(parent=Form)
        self.userinfo.setGeometry(QtCore.QRect(30, 10, 511, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.userinfo.setFont(font)
        self.userinfo.setObjectName("userinfo")
        self.access_info = QtWidgets.QLabel(parent=Form)
        self.access_info.setGeometry(QtCore.QRect(30, 70, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.access_info.setFont(font)
        self.access_info.setObjectName("access_info")
        self.profile_button = QtWidgets.QPushButton(parent=Form)
        self.profile_button.setGeometry(QtCore.QRect(540, 310, 141, 31))
        self.profile_button.setObjectName("profile_button")
        self.user_find_line = QtWidgets.QLineEdit(parent=Form)
        self.user_find_line.setGeometry(QtCore.QRect(420, 10, 181, 22))
        self.user_find_line.setText("")
        self.user_find_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.user_find_line.setObjectName("user_find_line")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(620, 10, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.error_found_user = QtWidgets.QLabel(parent=Form)
        self.error_found_user.setGeometry(QtCore.QRect(420, 40, 231, 20))
        self.error_found_user.setStyleSheet("color: red;")
        self.error_found_user.setText("")
        self.error_found_user.setObjectName("error_found_user")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(280, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.adduser = QtWidgets.QPushButton(parent=Form)
        self.adduser.setGeometry(QtCore.QRect(20, 310, 161, 31))
        self.adduser.setObjectName("adduser")
        self.adduser_2 = QtWidgets.QPushButton(parent=Form)
        self.adduser_2.setGeometry(QtCore.QRect(280, 310, 161, 31))
        self.adduser_2.setObjectName("adduser_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sections.setText(_translate("Form", "Отделы"))
        self.vacations.setText(_translate("Form", "Отпуска"))
        self.users.setText(_translate("Form", "Сотрудники"))
        self.userinfo.setText(_translate("Form", "TextLabel"))
        self.access_info.setText(_translate("Form", "Пользователь"))
        self.profile_button.setText(_translate("Form", "Профиль"))
        self.user_find_line.setPlaceholderText(_translate("Form", "Введите почту сотрудника"))
        self.pushButton.setText(_translate("Form", "Найти"))
        self.label.setText(_translate("Form", "Поиск сотрудника"))
        self.adduser.setText(_translate("Form", "Добавиль пользователя"))
        self.adduser_2.setText(_translate("Form", "Экспорт базы данных"))
