# Form implementation generated from reading ui file 'sections.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 560)
        Dialog.setMinimumSize(QtCore.QSize(700, 560))
        Dialog.setMaximumSize(QtCore.QSize(700, 560))
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: #2C2F33;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#3A3D42; \n"
"}")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 60, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.countler = QtWidgets.QLabel(parent=Dialog)
        self.countler.setGeometry(QtCore.QRect(350, 60, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.countler.setFont(font)
        self.countler.setText("")
        self.countler.setObjectName("countler")
        self.vacation_button = QtWidgets.QPushButton(parent=Dialog)
        self.vacation_button.setGeometry(QtCore.QRect(550, 10, 141, 31))
        self.vacation_button.setObjectName("vacation_button")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 160, 671, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.main_window_button = QtWidgets.QPushButton(parent=Dialog)
        self.main_window_button.setGeometry(QtCore.QRect(20, 10, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.main_window_button.setFont(font)
        self.main_window_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    color: darkblue;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#2C2F33; \n"
"}")
        self.main_window_button.setObjectName("main_window_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Количество отделов"))
        self.vacation_button.setText(_translate("Dialog", "Добавить отдел"))
        self.main_window_button.setText(_translate("Dialog", "Главное меню"))
