# Form implementation generated from reading ui file 'section_profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 560)
        Dialog.setMinimumSize(QtCore.QSize(900, 560))
        Dialog.setMaximumSize(QtCore.QSize(900, 560))
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: #2C2F33;\n"
"    color: #FFFFFF;\n"
"}\n"
"QPushButton {\n"
"    border: 2px solid white;\n"
"    border-radius: 5px; \n"
"    padding: 5px 10px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#3A3D42;\n"
"}")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 170, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.countler = QtWidgets.QLabel(parent=Dialog)
        self.countler.setGeometry(QtCore.QRect(350, 150, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.countler.setFont(font)
        self.countler.setText("")
        self.countler.setObjectName("countler")
        self.remove_section = QtWidgets.QPushButton(parent=Dialog)
        self.remove_section.setGeometry(QtCore.QRect(750, 90, 141, 41))
        self.remove_section.setObjectName("remove_section")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 220, 861, 331))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.main_window_button = QtWidgets.QPushButton(parent=Dialog)
        self.main_window_button.setGeometry(QtCore.QRect(20, 10, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.main_window_button.setFont(font)
        self.main_window_button.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    color: darkblue;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#2C2F33; \n"
"}")
        self.main_window_button.setObjectName("main_window_button")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.new_head = QtWidgets.QLineEdit(parent=Dialog)
        self.new_head.setGeometry(QtCore.QRect(510, 180, 231, 21))
        self.new_head.setText("")
        self.new_head.setObjectName("new_head")
        self.change_head = QtWidgets.QPushButton(parent=Dialog)
        self.change_head.setGeometry(QtCore.QRect(750, 170, 141, 41))
        self.change_head.setObjectName("change_head")
        self.error_label = QtWidgets.QLabel(parent=Dialog)
        self.error_label.setGeometry(QtCore.QRect(510, 150, 231, 20))
        self.error_label.setStyleSheet("color: red")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 110, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 60, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 60, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.add_position = QtWidgets.QPushButton(parent=Dialog)
        self.add_position.setGeometry(QtCore.QRect(750, 20, 141, 41))
        self.add_position.setObjectName("add_position")
        self.new_position = QtWidgets.QLineEdit(parent=Dialog)
        self.new_position.setGeometry(QtCore.QRect(510, 30, 231, 21))
        self.new_position.setText("")
        self.new_position.setObjectName("new_position")
        self.error_label_2 = QtWidgets.QLabel(parent=Dialog)
        self.error_label_2.setGeometry(QtCore.QRect(540, 10, 191, 20))
        self.error_label_2.setStyleSheet("color: red")
        self.error_label_2.setText("")
        self.error_label_2.setObjectName("error_label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Количество должностей"))
        self.remove_section.setText(_translate("Dialog", "Удалить отдел"))
        self.main_window_button.setText(_translate("Dialog", "Главное меню"))
        self.label_3.setText(_translate("Dialog", "Глава отдела"))
        self.new_head.setPlaceholderText(_translate("Dialog", "Почта нового главы"))
        self.change_head.setText(_translate("Dialog", "Изменить главу"))
        self.label_4.setText(_translate("Dialog", "Отдел"))
        self.add_position.setText(_translate("Dialog", "Добавить должность"))
        self.new_position.setPlaceholderText(_translate("Dialog", "Название должности"))
